class Services {
  static List<String> items = [
    "chirurgie viscérale",
    "chirurgie générale",
    "chirurgie cardio-vasculaire et thoracique",
    "chirurgie vasculaire périphérique",
    "orthopédie",
    "traumatologie",
    "urologie",
    "oto-rhino-laryngologie",
    "chirurgie maxillo-faciale",
    "ophtalmologie",
    "neurochirurgie",
    "gynécologie obstétrique",
    "médecine et chirurgie dentaire",
    "cardiologie",
    "gastro-entérologie",
    "anesthésie réanimation",
    "pneumo allergologie",
    "néphrologie",
    "endocrinologie",
    "neurologie",
    "psychiatrie",
    "dermatologie",
    "pédiatrie",
    "néonatologie",
    "hématologie",
  ];
}
